BarCejas.App/Areas/Admin/Controllers/GestorShiftsController.cs
using BarCejas.App.Utils;
using BarCejas.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using BarCejas.Entities.Enumerations;
using BarCejas.Entities;
using BarCejas.App.Models;
using OrderViewModel = BarCejas.App.Areas.Admin.Models.OrderViewModel;
using System.Globalization;
using Microsoft.AspNetCore.Mvc.Rendering;
using BarCejas.App.Areas.Admin.Models;
using System.IO;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace BarCejas.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[Controller]")]
    [Authorize(Roles = "Administrador, Profesional")]
    public class GestorShiftsController : BaseController
    {
        private readonly IServicioService _servicioService;
        private readonly IModalidadPagoService _modalidadPagoService;
        private readonly IFormaPagoService _formaPagoService;
        private readonly IContactoLocalService _contactoLocalService;
        private readonly IProfesionalService _profesionalService;
        private readonly IOrderService _orderService;
        private readonly IUsuarioService _usuarioService;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly string _imgRuta;

        public GestorShiftsController(IServicioService servicioService, IModalidadPagoService modalidadPagoService, IFormaPagoService formaPagoService, IContactoLocalService contactoLocalService, IProfesionalService profesionalService, IOrderService orderService, IUsuarioService usuarioService, IUnitOfWork unitOfWork, IHostingEnvironment hostingEnvironment, IConfiguration configuration)
        {
            _servicioService = servicioService;
            _modalidadPagoService = modalidadPagoService;
            _formaPagoService = formaPagoService;
            _contactoLocalService = contactoLocalService;
            _profesionalService = profesionalService;
            _orderService = orderService;
            _usuarioService = usuarioService;
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;
            _imgRuta = configuration.GetValue<string>("RutaImg");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            Usuario user = GetUserIdentity();

            ViewBag.ModalidadesPago = Util.GetItemsByEnumMedioPago();
            ViewBag.EstatusOrden = Util.GetItemsByEnumEstatusOrden();
            ViewBag.EstatusPago = Util.GetItemsByEnumEstatusPago();
            ViewBag.Servicios = Util.GetServicioSelectListItems(_servicioService.GetServicioAll());
            ViewBag.Profesionales = Util.GetProfesionalSelectListItems(await _profesionalService.GetProfesionalAllActive());

            ViewData["IsAdmin"] = user.IdTipoUsuario == (int)RoleType.Profesional ? false : true;


            List<OrdenesVigentes> ordenes = await _orderService.GetCurrentOrders(-1, -1, -1, -1, -1, -1, DateTime.Now, DateTime.Now.AddMonths(1));

            return View(ordenes.AsEnumerable());
        }

        [HttpPost]
        [Route("SearchTurns")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> List([FromForm] OrdenFilterViewModel filer)
        {
            try
            {
                Usuario user = GetUserIdentity();
                ViewData["IsAdmin"] = user.IdTipoUsuario == (int)RoleType.Profesional ? false : true;

                filer.FechaInicio = filer.FechaInicio is null || (filer.FechaInicio != null && DateTime.Compare(DateTime.Parse(filer.FechaInicio.ToString()), DateTime.MinValue) == 0) ? DateTime.Now : filer.FechaInicio;
                filer.FechaFin = filer.FechaFin is null || (filer.FechaFin != null && DateTime.Compare(DateTime.Parse(filer.FechaFin.ToString()), DateTime.MinValue) == 0) ? DateTime.Now.AddMonths(1) : filer.FechaFin;
                filer.IdProfesional = filer.IdProfesional > 0 ? filer.IdProfesional : -1;

                List<OrdenesVigentes> ordenes = await _orderService.GetCurrentOrders(-1, filer.IdServicio > 0 ? filer.IdServicio : -1, filer.IdProfesional, filer.IdModalidadPago > 0 ? filer.IdModalidadPago : -1, filer.IdEstatusOrden > 0 ? filer.IdEstatusOrden : -1, filer.IdEstatusPago > 0 ? filer.IdEstatusPago : -1, filer.FechaInicio, filer.FechaFin);
                return PartialView("_TurnosList", ordenes.Take(20));
            }
            catch (Exception ex)
            {
                return BadRequest(new { isCompleted = false, message = "Ha ocurrido un error interno en el servidor.", exception = ex });
            }
        }

        [HttpGet]
        [Route("New")]
        public IActionResult New()
        {
            try
            {
                ViewBag.Servicios = Util.GetServicioSelectListItems(_servicioService.GetServicioAll());
                ViewBag.ModalidadesPago = Util.GetItemsByEnumMedioPago();
                ViewBag.FormasPago = Util.GetItemsByEnumFormaPago();
                return PartialView("_AddOrEdit", new OrderViewModel());
            }
            catch (Exception ex)
            {
                return BadRequest(new { isCompleted = false, message = "Ha ocurrido un error interno en el servidor.", exception = ex });
            }
        }

        [HttpPost]
        [Route("Registre")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registre([FromForm] OrderViewModel model)
        {
            try
            {
                if (model != null)
                {
                    if (model.IdServicio == 0)
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione el servicio." });
                    if (model.IdContactoLocal == 0)
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione el local." });
                    if (model.IdProfesional == 0)
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione el profesional de servicio." });
                    if (model.IdCliente == 0)
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione el cliente." });
                    if (DateTime.Compare(model.FechaCita, DateTime.Now.Date) < 0)
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione una fecha valida." });
                    if (string.IsNullOrEmpty(model.Hora))
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione la hora del turno." });
                    if (model.IdFormaPago == 0)
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione la forma de pago." });
                    if (model.IdModalidadPago == 0)
                        return BadRequest(new { isCompleted = false, message = "Por favor seleccione la modalidad de pago." });
                    Orden orden = new Orden()
                    {
                        IdCliente = model.IdCliente,
                        IdContactoLocal = model.IdContactoLocal,
                        IdFormaPago = model.IdFormaPago,
                        IdModalidadPago = model.IdModalidadPago,
                        FechaDeCreacion = DateTime.Now,
                        IdEstatus = (int)EstatusOrden.pendiente,
                        IdEstatusPago = (int)EstatusPago.pendiente
                    };
                    orden = await _orderService.InsertOrder(orden);
                    if (orden.Id > 0)
                    {
                        List<OrdenItem> items = new List<OrdenItem>();
                        OrdenItem ordenItem = new OrdenItem()
                        {
                            FechaDeCita = model.FechaCita,
                            Hora = model.Hora,
                            IdOrden = orden.Id,
                            IdProfesional = model.IdProfesional,
                            IdServicio = (int)model.IdServicio,
                            Monto = model.Monto
                        };

                        items.Add(ordenItem);

                        if (await _orderService.InsertOrderItem(items))
                        {
                            Usuario user = GetUserIdentity();
                            ViewData["IsAdmin"] = user.IdTipoUsuario == (int)RoleType.Profesional ? false : true;

                            List<OrdenesVigentes> ordenes = await _orderService.GetCurrentOrders(-1, -1, -1, -1, -1, -1, DateTime.Now, DateTime.Now.AddMonths(1));
                            return PartialView("_TurnosList", ordenes.Take(20));
                        }
                        else
                            return BadRequest(new { isCompleted = false, message = "La acción no pudo ser completada." });
                    }
                    else
                        return BadRequest(new { isCompleted = false, message = "La acción no pudo ser completada." });
                }
                return BadRequest(new { isCompleted = false, message = "La acción no pudo ser completada." });
            }
            catch (Exception ex)
            {
                return BadRequest(new { isCompleted = false, message = "Ha ocurrido un error interno en el servidor.", exception = ex });
            }
        }

        [HttpGet]
        [Route("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                if (id > 0)
                {
                    List<OrdenesVigentes> ordenes = await _orderService.GetCurrentOrders(id, -1, -1, -1, -1, -1, null, null);
                    if (ordenes.Count > 0)
                    {
                        var orden = ordenes.FirstOrDefault();

BarCejas.App/Areas/Admin/Views/GestorShifts/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@model IEnumerable<BarCejas.Entities.OrdenesVigentes>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Gestor de turnos";
}

<section class="single-page-header">
    <diV class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <ol class="breadcrumb header-bradcrumb">
                    <li class="btn-trans"><a href="javascript:history.back()"><i class="fas fa-solid fa-angle-left"></i></a></li>
                    <li class="spa-bag"><a asp-controller="GestorShifts" asp-action="Inderx">Gestor</a></li>
                    <li class="spa-bag"></li>
                    <li class="active spa-bag">Gestor de turnos</li>
                </ol>
            </div>
        </div>
    </diV>


    <div class="container  title-secon-header">
        <div class="row">
            <div class="col-md-12">
                <h4 class="title-secon">GESTIONAR TURNOS</h4>
            </div>
        </div>
    </div>
</section>


<section class="about-shot-info section-sm">
    <div class="container">
        @await Html.PartialAsync("_TurnosFilter")
    </div>
</section>



<section class="company-mission section" style="padding-top: 2%;">
    <div class="container">
        <div class="row">
            <div class="col-md-12" id="ListTurnos">
                @await Html.PartialAsync("_TurnosList", Model)
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="TurnoModal" tabindex="-1" aria-labelledby="TurnoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="TurnoModalLabel"></h5>
                <a href="#" class="close" data-dismiss="modal" aria-label="close">&times;</a>
            </div>
            <div class="modal-body pl-5 pr-5" id="TurnoModalBody">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="clientModal" tabindex="-1" aria-labelledby="clientModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="clientModalLabel"></h5>
                <a href="#" class="close" data-dismiss="modal" aria-label="close">&times;</a>
            </div>
            <div class="modal-body pl-5 pr-5" id="clientModalBody">
            </div>
        </div>
    </div>
</div>

@section scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script type="text/javascript">
    var contentModalidadesPago =@Html.Raw(Json.Serialize(ViewBag.ModalidadesPago));
        OnLoadTable('#tbTurnos');

        function onFailureTurno(error) {
            OnFailureAddOrEdit(error);
        }
        function onBeginTurno() {
            $('#TurnoModalBody').html('');
        }
        function OnSuccessAddOrEditTurno() {
            ModalGeneral('', 'Accón completada con éxito.', true);
            $('.modal').modal('hide');
            OnLoadTable('#tbTurnos');
        }

        function OnSuccessFilterTurno() {
            OnLoadTable('#tbTurnos');
        }

        function onChangeService(element) {
            $("#Hora").val(0);
            $("#Monto").val(0);
            $("#FechaCita").val('');
            resetValues("#IdProfesional");
            resetValues("#IdContactoLocal");
            $('#IdContactoLocal, #IdProfesional, #FechaCita, #Hora').prop('disabled', 'disabled');
            if (element.value > 0) {
                $.get('@Url.Action("OnChangeService", "GestorShifts")', { id: element.value }, function (resp) {
                    if (resp !== undefined && resp.isCompleted) {
                        $("#Monto").val(resp.promotionalPrice);
                        loadSelectValue("#IdContactoLocal", resp.contactItems);
                        $('#IdContactoLocal').prop('disabled', false);
                    }
                })
                .fail(function (error) {
                    onFailureTurno(error);
                });
            }
        }

        function resetValues(element) {
            $(element).find('option')
                .remove()
                .end()
                .append('<option value="0">Seleccione una opción</option>')
                .val(0);
        }

        function loadSelectValue(element, data) {
            resetValues(element);
            if (data.length > 0) {
                $.each(data, function (index, itemData) {
                    $(element).append(new Option(itemData.text, itemData.value))
                });
            }
            $(element).val(0);
        }

        function onChangeContact(element) {
            $("#Hora").val(0);
            $("#FechaCita").val('');
            resetValues("#IdProfesional");
            $('#IdProfesional, #FechaCita, #Hora').prop('disabled', 'disabled');
            if (element.value > 0) {
                $.get('@Url.Action("OnChangeContactLocal", "GestorShifts")', { id: element.value, idService: $('#IdServicio').val() }, function (resp) {
                    if (resp !== undefined && resp.isCompleted) {
                        loadSelectValue("#IdProfesional", resp.professionalsItems);
                        $('#IdProfesional').prop('disabled', false);
                        $('#FechaCita').prop('disabled', false);
                    }
                })
                .fail(function (error) {
                    onFailureTurno(error);
                });
            }
        }

        function onChangeProfessional(element) {
            //$('#Hora').prop('disabled', 'disabled');
            if ($('#IdOrdenItem').val() > 0) {
                if (element.value > 0) {
                resetValues("#Hora");
                if (element.value > 0) {
                    $.get('@Url.Action("OnChangeDateService", "GestorShifts")', { date: $('#FechaCita').val(), idService: $('#IdServicio').val(), idContact: $('#IdContactoLocal').val(), idProfessional: element.value }, function (resp) {
                        if (resp !== undefined && resp.isCompleted) {
                            loadSelectValue("#Hora", resp.hours);
                            $('#Hora').prop('disabled', false);
                        }
                    })
                    .fail(function (error) {
                        OnFailureAddOrEdit(error);
                        $('#FechaCita').prop('disabled', false);
                    });
                }
            }
            }
        }

        function onChangeDate(element) {
            resetValues("#Hora");
            $('#Hora').prop('disabled', 'disabled');
            var idProfessional = $('#IdProfesional') === null ? 0 : $('#IdProfesional').val();
            if (element.value.length > 0) {
                $('#FechaCita').val(element.value);
                $.get('@Url.Action("OnChangeDateService", "GestorShifts")', { date: element.value, idService: $('#IdServicio').val(), idContact: $('#IdContactoLocal').val(), idProfessional: idProfessional }, function (resp) {
                    if (resp !== undefined && resp.isCompleted) {
                        loadSelectValue("#Hora", resp.hours);
                        $('#Hora').prop('disabled', false);
                    }
                })
                .fail(function (error) {
                    onFailureTurno(error);
                });
            }
    }

    function onChangeHour(element) {
        $('#Hora').val(element.value);
    }

        function onChangeFormaPago(element) {
            if (element.value > 0) {
                console.log(contentModalidadesPago);
                resetValues("#IdModalidadPago");
                var isCash = false;
                if (element.value == '@((int)BarCejas.Entities.Enumerations.FormaDePago.Efectivo)')
                    isCash = true;
                $.each(contentModalidadesPago, function (index, itemData) {
                    if (isCash == true) {
                        if (itemData.value == '@((int)BarCejas.Entities.Enumerations.MedioDePago.En_el_local)') {
                            $("#IdModalidadPago").append(new Option(itemData.text, itemData.value));
                        }
                    } else {
                        if (itemData.value != '@((int)BarCejas.Entities.Enumerations.MedioDePago.En_el_local)') {
                            $("#IdModalidadPago").append(new Option(itemData.text, itemData.value));
                        }
                    }
                });
                $('#IdModalidadPago').prop('disabled', false);
            }
        }

        function onChangeFormaPagoComprobante(element) {
            if (element.value > 0) {
                document.getElementById("seccionComprobante").style.display = "none";
                console.log(element.value != '@((int)BarCejas.Entities.Enumerations.FormaDePago.Efectivo)');
                if (element.value != '@((int)BarCejas.Entities.Enumerations.FormaDePago.Efectivo)') {
                    document.getElementById("seccionComprobante").style.display = "block";
                }
            }
        }

        function onClientSelect(id, name) {
            console.log(id);
            $('#Cliente').val(name);
            $('#IdCliente').val(id);
            $('#clientModal').modal('hide');
        }
</script>
}

BarCejas.App/Areas/Admin/Views/GestorShifts/_AddOrEdit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@model BarCejas.App.Areas.Admin.Models.OrderViewModel

<form asp-controller="GestorShifts" asp-action=@(ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit ? "Update" : "Registre") data-ajax="true" data-ajax-method="POST" data-ajax-failure="onFailureTurno" data-ajax-success="OnSuccessAddOrEditTurno" data-ajax-mode="replace" data-ajax-update="#ListTurnos">
    <div class="row centrar">
        <h4 class="text-center">@(ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit ? "EDITAR" : "NUEVO") TURNO</h4>
        <div class="form-group col-md-12 mb-12">
            <input asp-for="IdOrden" type="hidden" />
            <input asp-for="IdOrdenItem" type="hidden" />
            @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit)
            {
                <input asp-for="IdServicio" type="hidden" />
                <input asp-for="IdContactoLocal" type="hidden" />
                <input asp-for="FechaCita" type="hidden" />
                <input asp-for="IdModalidadPago" type="hidden" />
                <input asp-for="IdFormaPago" type="hidden" />
            }

            <label asp-for="IdServicio">Servicio</label>
            @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit)
            {
                <select class="form-control" asp-for="IdServicio" asp-items="(ViewBag.Servicios!=null?ViewBag.Servicios:null)" onchange="onChangeService(this)" disabled>
                    <option value="0">Seleccione una opción</option>
                </select>
            }
            else
            {
                <select class="form-control" asp-for="IdServicio" asp-items="(ViewBag.Servicios!=null?ViewBag.Servicios:null)" onchange="onChangeService(this)">
                    <option value="0">Seleccione una opción</option>
                </select>
            }
            <input asp-for="Monto" type="hidden" />
        </div>
        <div class="form-group col-md-12 mb-12">
            <label asp-for="IdContactoLocal">Local</label>
            <select class="form-control" asp-for="IdContactoLocal" asp-items="(ViewBag.ContactoLocales!=null?ViewBag.ContactoLocales:null)" onchange="onChangeContact(this)" disabled>
                <option value="0">Seleccione una opción</option>
            </select>
        </div>
        <div class="form-group col-md-12 mb-12">
            <label asp-for="IdProfesional">Profesional</label>
            @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit && ViewBag.Reprogramar)
            {
                <select class="form-control" asp-for="IdProfesional" asp-items="(ViewBag.Profesionales!=null?ViewBag.Profesionales:null)" onchange="onChangeProfessional(this)">
                    <option value="0">Seleccione una opción</option>
                </select>
            }
            else
            {
                <select class="form-control" asp-for="IdProfesional" asp-items="(ViewBag.Profesionales!=null?ViewBag.Profesionales:null)" onchange="onChangeProfessional(this)" disabled>
                    <option value="0">Seleccione una opción</option>
                </select>
            }

        </div>
        <div class="form-group col-md-12 mb-12">
            <label asp-for="Cliente">Cliente</label>
            <div class="input-group mb-3">
                <input asp-for="Cliente" type="text" class="form-control" disabled readonly placeholder="Cliente" />
                <input asp-for="IdCliente" type="hidden" class="form-control" />
                @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit)
                {
                    <button class="btn btn-main-accion float-right ml-3" type="button" disabled><i class="bi bi-search"></i></button>
                }
                else
                {
                    <a class="btn btn-main-accion float-right ml-3" data-toggle="modal" data-target="#clientModal" data-ajax="true" data-ajax-failure="onFailureTurno" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#clientModalBody" asp-controller="GestorShifts" asp-action="Clients"><i class="bi bi-search"></i></a>
                }
            </div>
        </div>
        <div class="form-group col-md-6 mb-6">
            <label asp-for="FechaCita">Fecha</label>
            <div class="md-form md-outline input-with-post-icon datepicker">
                @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit)
                {
                    if (ViewBag.Reprogramar)
                    {
                        <input placeholder="Select date" type="date" asp-for="FechaCita" class="form-control" onchange="onChangeDate(this)">
                    }
                    else
                    {
                        <input placeholder="Select date" type="date" asp-for="FechaCita" class="form-control" onchange="onChangeDate(this)" disabled>
                    }
                }
                else
                {
                    <input placeholder="Select date" type="date" asp-for="FechaCita" value="@string.Empty" class="form-control" onchange="onChangeDate(this)" disabled>
                }

            </div>
        </div>
        <div class="form-group col-md-6 mb-6">
            <label asp-for="Hora">Hora</label>
            @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit)
            {
                <select class="form-control" asp-for="Hora" onchange="onChangeHour(this)" disabled>
                    <option value="@Model.Hora" selected>@Model.Hora</option>
                </select>
            }
            else
            {
                <select class="form-control" asp-for="Hora" disabled>
                    <option value="0">Seleccione un horario</option>
                </select>
            }
        </div>
        <div class="form-group col-md-12 mb-12">
            <label asp-for="IdFormaPago">Medios de pago</label>
            @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit)
            {
                <select class="form-control" asp-for="IdFormaPago" asp-items="(ViewBag.FormasPago!=null?ViewBag.FormasPago:null)" disabled>
                    <option value="0">Seleccione una opción</option>
                </select>
            }
            else
            {
                <select class="form-control" asp-for="IdFormaPago" asp-items="(ViewBag.FormasPago!=null?ViewBag.FormasPago:null)" onchange="onChangeFormaPago(this)">
                    <option value="0">Seleccione una opción</option>
                </select>
            }

        </div>
        <div class="form-group col-md-12 mb-12">
            <label asp-for="IdModalidadPago">Modalidades de pago</label>
            @if (ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit)
            {
                <select class="form-control" asp-for="IdModalidadPago" asp-items="(ViewBag.ModalidadesPago!=null?ViewBag.ModalidadesPago:null)" disabled>
                    <option value="0">Seleccione una opción</option>
                </select>
            }
            else
            {
                <select class="form-control" asp-for="IdModalidadPago" disabled>
                    <option value="0">Seleccione una opción</option>
                </select>
            }

        </div>
    </div>

    <div class="row centrar">
        <div class="col-md-12 mb-4 centrar">
            <button class="btn btn-main-accion" type="submit">@(ViewBag.Action == BarCejas.Entities.Enumerations.Actions.Edit ? "EDITAR" : "CREAR") TURNO</button>
        </div>
    </div>
</form>

BarCejas.App/Areas/Admin/Views/GestorShifts/_CancelShift.cshtml
@model BarCejas.Entities.OrdenesVigentes


<form asp-controller="GestorShifts" asp-action="OnChangeEstatus" data-ajax="true" data-ajax-method="POST" data-ajax-failure="onFailureTurno" data-ajax-success="OnSuccessAddOrEditTurno" data-ajax-mode="replace" data-ajax-update="#ListTurnos">
    <input asp-for="IdOrden" type="hidden" />
    <h4 class="text-center">
        ¿Deseas cancelar tu turno
        del cliente @Model.Cliente
        el @Model.FechaDeCita.ToShortDateString() a las @Model.Hora?
    </h4>
    <div class="row centrar">
        <div class="col-md-12 mb-4 centrar ">
            <a href="#" style="width: 100%;" data-dismiss="modal" class="btn btn-main">VOLVER</a>
        </div>
        <div class="col-md-12 mb-4 centrar">
            <button type="submit" class="btn btn-main-accion" style="width: 100%;">CANCELAR TURNO</button>
        </div>
    </div>
</form>

BarCejas.App/Areas/Admin/Views/GestorShifts/_ClientList.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@model IEnumerable<BarCejas.Entities.Usuario>

<table id="example" class="table">
    <thead>
        <tr>
            <th>DNI</th>
            <th>Nombre</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model is null)
        {
            <tr>
                <td>No existen elementos</td>
            </tr>
        }
        else
        {

            foreach (BarCejas.Entities.Usuario item in Model)
            {
                <tr>
                    <td>@item.Dni</td>
                    <td>@($"{item.Nombre} {item.Apellido}")</td>
                    <td>@item.Email</td>
                    <td><button class="btn btn-main" id="client_@item.Id" onclick="onClientSelect(@($"{item.Id}"),'@($"{item.Nombre} {item.Apellido}")')">Seleccionar</button></td>
                </tr>
            }
        }
    </tbody>
</table>

BarCejas.App/Areas/Admin/Views/GestorShifts/_ClientModal.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

<div class="container">
    <div class="row">
        <form asp-controller="GestorShifts" asp-action="SearchClient" data-ajax="true" data-ajax-method="get" data-ajax-failure="onFailureTurno" data-ajax-mode="replace" data-ajax-update="#clientList">
            <div class="col-md-12">
                <div class="row">
                    <div class="input-group col-md-3 mb-3">
                        <input type="text" class="form-control" name="nombre" placeholder="Nombre del cliente">
                    </div>
                    <div class="form-group col-md-3 mb-3">
                        <input type="text" class="form-control" name="apellido" placeholder="Apellido del cliente">
                    </div>
                    <div class="input-group col-md-3 mb-3">
                        <input type="text" class="form-control" name="dni" placeholder="DNI del cliente">
                    </div>
                    <div class="input-group col-md-3 mb-3">
                        <button type="submit" class="btn btn-main">Buscar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12" id="clientList">
            @await Html.PartialAsync("_ClientList", null)
        </div>
    </div>
</div>

BarCejas.App/Areas/Admin/Views/GestorShifts/_VoucherModal.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@model BarCejas.Entities.Orden

<div class="row centrar">
    <h4 class="text-center">COMPROBANTE DE PAGO</h4>
    <div class="form-group col-md-12 mb-12">
        @if (!String.IsNullOrEmpty(Model.ComprobantePago))
        {
            <img class="img-fluid course_img_center" src="@(!String.IsNullOrEmpty(Model.ComprobantePago) ?  Url.Content(Model.ComprobantePago):Url.Content("~/images/sinImagen.png"))" asp-append-version="true" alt="" />
        }
        else
        {
            <p>No existe un comprobante asociado</p>
        }
    </div>
</div>