BarCejas.App/Areas/Admin/Controllers/GestorMensajeMasivoController.cs
using BarCejas.Data.Interfaces;
using BarCejas.Entities;
using BarCejas.Entities.Enumerations;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BarCejas.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrador")]
    public class GestorMensajeMasivoController : BaseController
    {
        private readonly IMensajeMasivoService _serviceMensajeMasivo;

        public GestorMensajeMasivoController(IMensajeMasivoService serviceMensajeMasivo)
        {
            _serviceMensajeMasivo = serviceMensajeMasivo;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<MensajeMasivo> lMensajeMasivo;
            lMensajeMasivo = await _serviceMensajeMasivo.GetMensajeMasivoAll();
            return View(lMensajeMasivo);
        }

        public async Task<IActionResult> _Listado()
        {
            IEnumerable<MensajeMasivo> lMensajeMasivo;
            lMensajeMasivo = await _serviceMensajeMasivo.GetMensajeMasivoAll();
            return PartialView(lMensajeMasivo);
        }

        [HttpGet]
        public async Task<IActionResult> Create_Edit(int Id = 0)
        {
            List<RoleType> lRol = Enum.GetValues(typeof(RoleType))
                               .Cast<RoleType>()
                               .ToList();

            ViewBag.lRol = lRol;
            if (Id > 0)
            {
                MensajeMasivo MensajeMasivo;
                MensajeMasivo = await _serviceMensajeMasivo.GetMensajeMasivoById(Id);
                if (MensajeMasivo != null && MensajeMasivo.Id > 0)
                    return View(MensajeMasivo);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create_Edit(MensajeMasivo model)
        {
            Usuario usuario = GetUserIdentity();
            bool resultado = false,
                 procesar = true;
            string Mensaje = "Disuclpe, no fue posible procesar su solicitud.",
                   MensajeError = string.Empty;
            if (model.Id == 0)
            {
                model.EsEliminado = false;
            }

            try
            {
                if (string.IsNullOrEmpty(model.Asunto))
                {
                    procesar = false;
                    Mensaje = "Debe ingresar un asunto.";
                }
                if (string.IsNullOrEmpty(model.Mensaje))
                {
                    procesar = false;
                    Mensaje += "Debe ingresar un mensaje.";
                }
                if (model.RolTipoUsuarioMensajeMasivo == null || model.RolTipoUsuarioMensajeMasivo.Count == 0)
                {
                    procesar = false;
                    Mensaje += "Debe seleccionar el tipo de usuarios que recibirá la notificación.";
                }
                else
                {

                    for (int i = 0; i < model.RolTipoUsuarioMensajeMasivo.Count(); i++)
                    {
                        model.RolTipoUsuarioMensajeMasivo.ToArray()[i].EsActivo = true;
                        if (model.Id > 0)
                            model.RolTipoUsuarioMensajeMasivo.ToArray()[i].IdMensajeMasivo = model.Id;
                    }

                }

                if (procesar)
                {
                    model.FechaModificacion = DateTime.Now;
                    model.EsEliminado = false;
                    if (model.Id > 0)
                    {
                        model.IdUsuarioModificacion = usuario.Id;
                        resultado = await _serviceMensajeMasivo.UpdateMensajeMasivo(model);
                        Mensaje = resultado ? "Registro editado satisfactoriamente." : Mensaje;
                    }
                    else
                    {
                        model.IdUsuarioAlta = usuario.Id;
                        model.IdUsuarioModificacion = usuario.Id;
                        model.FechaAlta = model.FechaModificacion;
                        await _serviceMensajeMasivo.InsertMensajeMasivo(model);
                        Mensaje = "Registro creado satisfactoriamente.";
                        resultado = true;
                    }
                    return Json(new { success = resultado, mensaje = Mensaje });
                }
            }
            catch (Exception e)
            {
                MensajeError = e.Message;
            }

            return Json(new { success = resultado, mensaje = Mensaje, MensajeError = MensajeError });
        }

        public async Task<IActionResult> Delete(int Id = 0)
        {
            bool success = false;
            string Mensaje = "Disculpe, debe ingresar datos válidos";
            if (Id > 0)
            {
                MensajeMasivo mensajeMasivo = new MensajeMasivo();
                mensajeMasivo = await _serviceMensajeMasivo.GetMensajeMasivoById(Id);
                if (mensajeMasivo != null && mensajeMasivo.Id > 0)
                {
                    mensajeMasivo.EsEliminado = mensajeMasivo.EsEliminado ? false : true;
                    mensajeMasivo.FechaModificacion = DateTime.Now;
                    success = await _serviceMensajeMasivo.UpdateMensajeMasivo(mensajeMasivo);
                    if (success)
                        Mensaje = "Registro actualizado satisfactoriamente.";
                    else
                        Mensaje = "Disculpe, no fue posible actualizar el registro.";
                }
            }
            return Json(new { success = success, mensaje = Mensaje });
        }
    }
}

BarCejas.App/Areas/Admin/Views/GestorMensajeMasivo/Create_Edit.cshtml
@model BarCejas.Entities.MensajeMasivo
@using BarCejas.Entities;
@using BarCejas.Entities.Enumerations;

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@{
    ViewData["Title"] = Model != null && Model.Id > 0 ? "Editar" : "Crear";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

    int RolTipoUsuarioMensajeMasivo = (Model != null &&
                                     Model.RolTipoUsuarioMensajeMasivo != null &&
                                     Model.RolTipoUsuarioMensajeMasivo.Count > 0

      ? Model.RolTipoUsuarioMensajeMasivo.First().IdTipoUsuario : 0);
}

<section class="single-page-header">
    <diV class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <ol class="breadcrumb header-bradcrumb">
                    <li class="btn-trans"><a href="javascript:history.back()"><i class="fas fa-solid fa-angle-left"></i></a></li>
                    <li class="spa-bag"><a asp-controller="GestorMensajeMasivo" asp-action="Index" asp-area="Admin">Gestor</a></li>
                    <li class="spa-bag">-</li>
                    <li class="active spa-bag">Gestor de mensaje masivo</li>
                </ol>
            </div>
        </div>
    </diV>
    <div class="container title-secon-header">
        <div class="row">
            <div class="col-md-12">
                @if (Model != null && Model.Id > 0)
                {
                    <h4 class="title-secon">EDITAR MENSAJE MASIVO</h4>
                }
                else
                {
                    <h4 class="title-secon">CREAR MENSAJE MASIVO</h4>
                }
            </div>
        </div>
    </div>
</section>

<section class="company-mission section" style="padding-top: 68px!important;">
    <div class="container">
        <form asp-action="Create_Edit" method="post" data-ajax="true" data-ajax-failure="fnOnFailed" data-ajax-success="fnOnSuccess" data-content="false">
            <div class="row">
                <div style="display:none">
                    @if (Model != null && Model.Id > 0)
                    {
                        <input asp-for="Id" />
                        <input asp-for="FechaAlta" />
                        <input asp-for="IdUsuarioAlta" />
                    }

                </div>

                <div class="col-md-8">
                    <div class="row">
                        <div class="form-group col-md-12 mb-12">
                            <label for="Asunto">Asunto</label>
                            <input type="text" class="form-control" asp-for="Asunto" placeholder="Asunto">
                            <span asp-validation-for="Asunto" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12 mb-5">
                            <label for="Mensaje">Mensaje completo</label>
                            <textarea asp-for="Mensaje"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h4 class="title-secon">Configuración de envios</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12 mb-12">
                            <label for="inputEmail4">Roles</label>
                            <select class="form-control" name="RolTipoUsuarioMensajeMasivo[0].IdTipoUsuario" id="exampleFormControlSelect1">
                                @foreach (var item in Enum.GetValues(typeof(RoleType)).Cast<int>())
                                {
                                    if (RolTipoUsuarioMensajeMasivo == item)
                                    {
                                        <option value="@item" selected>@Enum.GetName(typeof(RoleType), item)</option>
                                    }
                                    else
                                    {
                                        <option value="@item">@Enum.GetName(typeof(RoleType), item)</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="form-group col-md-12 mb-12">
                            <label for="inputEmail4">Vista previa notificación push</label>
                            <div class="phone">
                                <input type="text" class="phoneImput" id="inputphone" placeholder="Vista previa">
                            </div>
                        </div>
                        <div class="col-md-12 mb-12">
                            <button type="submit" class="btn btn-main-accion allWidth btn-block">ENVIAR</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6 col-sm-12 mb-4">
                    <a href="@Url.Action("Index", "GestorMensajeMasivo")" class="btn btn-main float-right allWidth">DESCARTAR</a>
                </div>
                <!-- <div class="form-group col-md-6 col-sm-12 mb-4">
                    <a class="btn btn-main-accion allWidth"  id="crearbtn">CREAR MENSAJE MASIVO</a>
                </div> -->
            </div>
        </form>

    </div>
</section>


@section scripts{

    <!-- CKEditor Script -->
    <script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(document).ready(function () {

            CKEDITOR.replace('Mensaje',
                {
                    allowedContent: true,
                    enterMode: CKEDITOR.ENTER_BR,
                }).on('key',
                    function (e) {
                        setTimeout(function () {
                            $("#inputphone").val(e.editor.getData());
                        }, 10);
                    }
                );
        });

        function fnOnSuccess(Data) {
            var url = '';
            if (Data.success){
                url = '@Url.Action("Index", "GestorMensajeMasivo")';
            } else {
                console.log('Disculpe, ha ocurrido un error.');
                console.log(Data);
            }
            ModalGeneral(url, Data.mensaje, Data.success);
        }

        function fnOnFailed(Data) {
            alert('Disculpe, ha ocurrido un error.');
            console.log(Data);
        }

    </script>

}

BarCejas.App/Areas/Admin/Views/GestorMensajeMasivo/Index.cshtml
@model IEnumerable<BarCejas.Entities.MensajeMasivo>
@using BarCejas.Entities;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="single-page-header">
    <diV class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <ol class="breadcrumb header-bradcrumb">
                    <li class="btn-trans">
                        <a href="javascript:history.back()">
                            <i class="fas fa-solid fa-angle-left"></i>
                        </a>
                    </li>
                    <li class="spa-bag"><a href="@Url.Action("Index")">Home</a></li>
                    <li class="spa-bag">-</li>
                    <li class="active spa-bag">Mensajes masivos</li>
                </ol>
            </div>
        </div>
    </diV>


    <div class="container title-secon-header">
        <div class="row">
            <div class="col-md-12">
                <h4 class="title-secon">GESTIONAR MENSAJES MASIVOS</h4>
            </div>
        </div>
    </div>
</section>

<section class="about-shot-info section-sm">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p>
                    El objetivo es gestionar la comunicación de los clientes de manera masiva. Los mensajes se envian
                    como notificación push. Se pueden programar para enviar de inmediato o definir que día sera
                    enviado.
                </p>
            </div>
            <div class="col-md-4">
                <a class="btn btn-main-accion float-right" href="@Url.Action("Create_Edit")">CREAR MENSAJE</a>
            </div>

        </div>
    </div>
</section>


<section class="company-mission section" style="padding-top: 2%;">
    <div class="container">
        <div class="row">
            <div class="col-md-12" id="divListado">

                <partial name="_Listado" model="Model" />

            </div>
        </div>
    </div>
</section>

@section scripts{

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">

        $(document).ready(function () {
            var table = $('#example').DataTable(
                {
                    dom: 'Bfrtip',
                    buttons: [
                        'copy', 'csv', 'excel', 'pdf', 'print'
                    ],
                    language: {
                        "decimal": "",
                        "emptyTable": "No hay datos",
                        "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
                        "infoEmpty": "Mostrando 0 a 0 de 0 registros",
                        "infoFiltered": "(Filtro de _MAX_ total registros)",
                        "infoPostFix": "",
                        "thousands": ",",
                        "lengthMenu": "Mostrar _MENU_ registros",
                        "loadingRecords": "Cargando...",
                        "processing": "Procesando...",
                        "search": "Buscar:",
                        "zeroRecords": "No se encontraron coincidencias",
                        "paginate": {
                            "first": "Primero",
                            "last": "Ultimo",
                            "next": "Próximo",
                            "previous": "Anterior"
                        },
                        "aria": {
                            "sortAscending": ": Activar orden de columna ascendente",
                            "sortDescending": ": Activar orden de columna desendente"
                        }
                    },
                    responsive: true

                }
            );

            new $.fn.dataTable.FixedHeader(table);
        });

        function ModalEliminarElemento(url, obj, msj = "¿Está seguro que desea eliminar el item seleccionado?", NombreItem = "Título del banner") {

            $(".swal2-title").removeClass("swal2-title");
            swal.fire({
                title: msj,
                text: NombreItem,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: "Si",
                cancelButtonText: "Cancelar",
                customClass: {
                    title: 'swal2-title-Warning'
                }

            }).then((result) => {
                if (result.isConfirmed) {
                    EliminarItemList(url, obj);
                }
                return false;
            });
        }

        function EliminarItemList(url, obj) {
            $.post(url, obj, function (Data) {
                var urlRedirect = '';
                if (Data.success) {
                    urlRedirect = '@Url.Action("Index", "GestorMensajeMasivo")';
                } else {
                    console.log('Disculpe, ha ocurrido un error.');
                    console.log(Data);
                }
                ModalGeneral(urlRedirect, Data.mensaje, Data.success);
            }).fail(function (error) {
                console.log(error);
            });
        }

    </script>

}

BarCejas.App/Areas/Admin/Views/GestorMensajeMasivo/_Listado.cshtml
@model IEnumerable<BarCejas.Entities.MensajeMasivo>
@using BarCejas.Entities.Enumerations

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

@{ 

    string RolesMensaje(List<int> lst) {

        string result = string.Empty;

        lst.ForEach(x =>
            result += (string.IsNullOrEmpty(result) ? "" : ", ")  + Enum.GetName(typeof(RoleType), x) 
        );

        return result;
    }

}

<table id="example" class="table" style="width:100%">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Horario</th>
            <th>Asunto</th>
            <th>Roles</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FechaAlta.ToString("dd/MM/yyyy")</td>
                <td>@item.FechaAlta.ToString("HH:mm")</td>
                <td>@item.Asunto</td>
                <td>@(RolesMensaje(item.RolTipoUsuarioMensajeMasivo.Select(s => s.IdTipoUsuario).ToList()))</td>
                <td><a class="btn btn-cir" href="@Url.Action("Create_Edit", new { Id = item.Id })"><i class="fas fa-light fa-pen"></i></a></td>
                <td><a class="btn btn-cir" onclick="ModalEliminarElemento('@Url.Action("Delete", "GestorMensajeMasivo")', { Id: @item.Id }, '¿Está seguro que desea eliminar el mensaje?', '@item.Asunto')"><i class="fas fa-solid fa-trash"></i></a></td>
            </tr>
        }
    </tbody>

</table>